/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Admin: () => import('#controllers/admin/admin_controller'),
    SeoSetting: () => import('#controllers/admin/seo_setting_controller'),
  },
  Football: () => import('#controllers/football_controller'),
  Page: () => import('#controllers/page_controller'),
  User: () => import('#controllers/user_controller'),
}
